rebuild Makefile.in and configure

diff --git a/mbdyn/configure b/mbdyn/configure
--- a/mbdyn/configure
+++ b/mbdyn/configure
@@ -2626,7 +2626,7 @@ METIS_LIBS=
 UMFPACK3_LIBS=
 MESCHACH_LIBS=
 HARWELL_LIBS=
-PAM_LIBS=
+LAPACK_LIBS=
 SECURITY_LIBS=
 TCL_LIBS=
 
@@ -3932,6 +3932,7 @@ if test $ol_link_meschach = no \
 	{ echo "configure: error: Need at least one (sparse) solver" 1>&2; exit 1; }
 fi
 
+
 ol_link_lapack=no
 if test $ol_with_lapack != no ; then
 	# MBDyn --with-lapack-[{inc|lib}]dir
@@ -3955,7 +3956,7 @@ ac_compile='${F77-f77} -c $FFLAGS conftest.$ac_ext 1>&5'
 ac_link='${F77-f77} -o conftest${ac_exeext} $FFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
 cross_compiling=$ac_cv_prog_f77_cross
 
-echo "configure:3959: checking for dgesvd in -llapack" >&5
+echo "configure:3960: checking for dgesvd in -llapack" >&5
 echo "configure:4944: checking for dgesvd in -llapack" >&5
 ac_lib_var=`echo lapack'_'dgesvd | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
@@ -3968,7 +3969,7 @@ cat > conftest.$ac_ext <<EOF
       program main
       call dgesvd()
       end
-if { (eval echo configure:3972: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:3973: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
 if { (eval echo configure:4957: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
@@ -4015,7 +4016,7 @@ ac_compile='${F77-f77} -c $FFLAGS conftest.$ac_ext 1>&5'
 ac_link='${F77-f77} -o conftest${ac_exeext} $FFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
 cross_compiling=$ac_cv_prog_f77_cross
 
-echo "configure:4019: checking for dgegv in -llapack" >&5
+echo "configure:4020: checking for dgegv in -llapack" >&5
 echo "configure:5004: checking for dgegv in -llapack" >&5
 ac_lib_var=`echo lapack'_'dgegv | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
@@ -4028,7 +4029,7 @@ cat > conftest.$ac_ext <<EOF
       program main
       call dgegv()
       end
-if { (eval echo configure:4032: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:4033: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
 if { (eval echo configure:5017: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
@@ -4058,6 +4059,7 @@ ac_link='${CC-cc} -o conftest${ac_exeext} $CFLAGS $CPPFLAGS $LDFLAGS conftest.$a
 cross_compiling=$ac_cv_prog_cc_cross
 
 
+	if test $have_lapack != no ; then
 		ol_link_lapack=yes
 		cat >> confdefs.h <<\EOF
 #define HAVE_DGEGV 1
@@ -4087,17 +4089,17 @@ if test $ol_with_pam != no ; then
 	for ac_hdr in security/pam_appl.h pam_misc.h security/pam_misc.h
 do
 ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
-echo "configure:4091: checking for $ac_hdr" >&5
+echo "configure:4093: checking for $ac_hdr" >&5
 echo "configure:5077: checking for $ac_hdr" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
-#line 4096 "configure"
+#line 4098 "configure"
 #line 5082 "configure"
 #include "confdefs.h"
 #include <$ac_hdr>
 EOF
-{ (eval echo configure:4101: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:4103: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 { (eval echo configure:5087: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
@@ -4128,7 +4130,7 @@ done
 	if test $ac_cv_header_security_pam_appl_h = yes ; then
 		if test $ac_cv_header_pam_misc_h = yes \
 			-o $ac_cv_header_security_pam_misc_h = yes ; then
-echo "configure:4132: checking for pam_start in -lpam" >&5
+echo "configure:4134: checking for pam_start in -lpam" >&5
 echo "configure:5118: checking for pam_start in -lpam" >&5
 ac_lib_var=`echo pam'_'pam_start | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
@@ -4136,7 +4138,7 @@ if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
 else
   ac_save_LIBS="$LIBS"
 LIBS="-lpam -lcrypt -lpam_misc -ldl $LIBS"
-#line 4140 "configure"
+#line 4142 "configure"
 #line 5126 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
@@ -4147,7 +4149,7 @@ char pam_start();
 int main() {
 pam_start()
 ; return 0; }
-if { (eval echo configure:4151: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:4153: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
 if { (eval echo configure:5137: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
@@ -4170,7 +4172,7 @@ have_pam=no
 fi
 
 			
-				PAM_LIBS="-lcrypt -lpam -lpam_misc -ldl"
+			if test $have_pam != no ; then
 				SECURITY_LIBS="-lcrypt -lpam -lpam_misc -ldl"
 				cat >> confdefs.h <<\EOF
 #define USE_PAM 1
@@ -4191,8 +4193,56 @@ EOF
 	fi
 else
 	echo "configure: warning: PAM not supported!" 1>&2
-		
+fi
+
+
+echo "configure:4200: checking how to link crypt" >&5
+echo "configure:5184: checking how to link crypt" >&5
+crypt_pool="\"\" -lcrypt -lcrypto"
+for i in $crypt_pool ; do
+	save_LIBS=$LIBS
+	LIBS="$LIBS $i"
+#line 4206 "configure"
+#line 5190 "configure"
+#include "confdefs.h"
+
+		#include <unistd.h>
+		#include <pwd.h>
+	
+int main() {
+
 		crypt(NULL,NULL);
+	
+; return 0; }
+if { (eval echo configure:4218: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:5202: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  crypt_ok=yes
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  crypt_ok=no
+fi
+rm -f conftest*
+	LIBS=$save_LIBS
+
+	if test $crypt_ok = yes ; then
+		if test "x$i" = "x" ; then
+			echo "$ac_t""automatically linked" 1>&6
+		else
+			echo "$ac_t""with $i" 1>&6
+			SECURITY_LIBS="$SECURITY_LIBS $i"
+		fi
+		break
+	fi
+done
+
+if test $crypt_ok != yes ; then
+	echo "$ac_t""no" 1>&6
+	echo "configure: warning: don't know how to link crypt..." 1>&2
+fi
+
 
 ol_link_mpi=no
 if test $ol_with_mpi != no ; then
@@ -4212,17 +4262,17 @@ if test $ol_with_mpi != no ; then
 # end --with-mpi-[{inc|lib}]dir
 
 	ac_safe=`echo "mpi.h" | sed 'y%./+-%__p_%'`
-echo "configure:4216: checking for mpi.h" >&5
+echo "configure:4266: checking for mpi.h" >&5
 echo "configure:5250: checking for mpi.h" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
-#line 4221 "configure"
+#line 4271 "configure"
 #line 5255 "configure"
 #include "confdefs.h"
 #include <mpi.h>
 EOF
-{ (eval echo configure:4226: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:4276: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 { (eval echo configure:5260: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
@@ -4252,17 +4302,17 @@ ac_link='${CXX-g++} -o conftest${ac_exeext} $CXXFLAGS $CPPFLAGS $LDFLAGS conftes
 cross_compiling=$ac_cv_prog_cxx_cross
 
 	ac_safe=`echo "mpi++.h" | sed 'y%./+-%__p_%'`
-echo "configure:4256: checking for mpi++.h" >&5
+echo "configure:4306: checking for mpi++.h" >&5
 echo "configure:5290: checking for mpi++.h" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
-#line 4261 "configure"
+#line 4311 "configure"
 #line 5295 "configure"
 #include "confdefs.h"
 #include <mpi++.h>
 EOF
-{ (eval echo configure:4266: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:4316: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 { (eval echo configure:5300: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
@@ -4293,7 +4343,7 @@ cross_compiling=$ac_cv_prog_cc_cross
 
 	
 	if test $ac_cv_header_mpi_h = yes -a $ac_cv_header_mpipp_h = yes ; then
-echo "configure:4297: checking for mpi libraries" >&5
+echo "configure:4347: checking for mpi libraries" >&5
 echo "configure:5331: checking for mpi libraries" >&5
 		ac_ext=C
 # CXXFLAGS is not in ac_cpp because -g, -O, etc. are not valid cpp options.
@@ -4305,7 +4355,7 @@ cross_compiling=$ac_cv_prog_cxx_cross
 		try_mpi_LIBS="-lmpich++ -lmpich -lnsl"
 		save_LIBS=$LIBS
 		LIBS="$LIBS $try_mpi_LIBS"
-#line 4309 "configure"
+#line 4359 "configure"
 #line 5343 "configure"
 #include "confdefs.h"
 #include <mpi++.h>
@@ -4316,7 +4366,7 @@ int main() {
 			MPI::Init(argc, argv);
 		
 ; return 0; }
-if { (eval echo configure:4320: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:4370: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
 if { (eval echo configure:5354: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   have_mpi=yes
@@ -4400,17 +4450,17 @@ if test $ol_with_metis != no ; then
 		for ac_hdr in metis.h
 do
 ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
-echo "configure:4404: checking for $ac_hdr" >&5
+echo "configure:4454: checking for $ac_hdr" >&5
 echo "configure:5438: checking for $ac_hdr" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
-#line 4409 "configure"
+#line 4459 "configure"
 #line 5443 "configure"
 #include "confdefs.h"
 #include <$ac_hdr>
 EOF
-{ (eval echo configure:4414: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:4464: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 { (eval echo configure:5448: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
@@ -4439,7 +4489,7 @@ done
 
 
 		if test $ac_cv_header_metis_h = yes ; then
-echo "configure:4443: checking for METIS_PartGraphVKway in -lmetis" >&5
+echo "configure:4493: checking for METIS_PartGraphVKway in -lmetis" >&5
 echo "configure:5477: checking for METIS_PartGraphVKway in -lmetis" >&5
 ac_lib_var=`echo metis'_'METIS_PartGraphVKway | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
@@ -4447,7 +4497,7 @@ if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
 else
   ac_save_LIBS="$LIBS"
 LIBS="-lmetis  $LIBS"
-#line 4451 "configure"
+#line 4501 "configure"
 #line 5485 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
@@ -4458,7 +4508,7 @@ char METIS_PartGraphVKway();
 int main() {
 METIS_PartGraphVKway()
 ; return 0; }
-if { (eval echo configure:4462: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:4512: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
 if { (eval echo configure:5496: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
@@ -4510,6 +4560,18 @@ else
 fi
 
 
+if test $ol_link_lapack != no -o $ol_link_meschach != no ; then
+	cat >> confdefs.h <<\EOF
+#define USE_DBC 1
+EOF
+
+else
+	if test $ol_with_elec != no ; then
+		echo "configure: warning: GPC/Deadbeat not allowed!" 1>&2
+	fi
+fi
+fi
+
 	getcwd \
 	getopt \
 	memset \
@@ -4518,12 +4580,12 @@ fi
 	strtol \
 
 do
-echo "configure:4522: checking for $ac_func" >&5
+echo "configure:4584: checking for $ac_func" >&5
 echo "configure:5593: checking for $ac_func" >&5
 if eval "test \"`echo '$''{'ac_cv_func_$ac_func'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
-#line 4527 "configure"
+#line 4589 "configure"
 #line 5598 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
@@ -4546,7 +4608,7 @@ $ac_func();
 #endif
 
 ; return 0; }
-if { (eval echo configure:4550: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:4612: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
 if { (eval echo configure:5621: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func_$ac_func=yes"
@@ -4573,7 +4635,6 @@ done
 
 
 
-
 ac_ext=C
 # CXXFLAGS is not in ac_cpp because -g, -O, etc. are not valid cpp options.
 ac_cpp='$CXXCPP $CPPFLAGS'
@@ -4581,9 +4642,9 @@ ac_compile='${CXX-g++} -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext 1>&5'
 ac_link='${CXX-g++} -o conftest${ac_exeext} $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
 cross_compiling=$ac_cv_prog_cxx_cross
 
-echo "configure:4585: checking whether class ostream has method 'form'" >&5
+echo "configure:4646: checking whether class ostream has method 'form'" >&5
 echo "configure:5655: checking whether class ostream has method 'form'" >&5
-#line 4587 "configure"
+#line 4648 "configure"
 #line 5657 "configure"
 #include "confdefs.h"
 #include <iostream.h>
@@ -4592,7 +4653,7 @@ int main() {
 	cout.form("%d", 1);
 
 ; return 0; }
-if { (eval echo configure:4596: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:4657: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
 if { (eval echo configure:5666: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   have_form=yes
@@ -4630,9 +4691,9 @@ ac_compile='${CXX-g++} -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext 1>&5'
 ac_link='${CXX-g++} -o conftest${ac_exeext} $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
 cross_compiling=$ac_cv_prog_cxx_cross
 
-echo "configure:4634: checking whether class ios has fmtflags type" >&5
+echo "configure:4695: checking whether class ios has fmtflags type" >&5
 echo "configure:5704: checking whether class ios has fmtflags type" >&5
-#line 4636 "configure"
+#line 4697 "configure"
 #line 5706 "configure"
 #include <iostream.h>
 #include <iostream>
@@ -4641,7 +4702,7 @@ int main() {
 	std::ios::fmtflags f;
 
 ; return 0; }
-if { (eval echo configure:4645: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:4706: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
 if { (eval echo configure:5715: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   have_fmtflags=yes
@@ -4831,7 +4892,7 @@ s%@F2C_LIBS@%$F2C_LIBS%g
 s%@MPI_LIBS@%$MPI_LIBS%g
 s%@UMFPACK3_LIBS@%$UMFPACK3_LIBS%g
 s%@MESCHACH_LIBS@%$MESCHACH_LIBS%g
-s%@PAM_LIBS@%$PAM_LIBS%g
+s%@LAPACK_LIBS@%$LAPACK_LIBS%g
 s%@SECURITY_LIBS@%$SECURITY_LIBS%g
 s%@TCL_LIBS@%$TCL_LIBS%g
 s%@Y12_LIBS@%$Y12_LIBS%g
